- name: Get swap_state
  shell: swapon -v
  register: swap_state
  check_mode: false
  changed_when: false

- name: Disable swap
  shell: swapoff -a
  when: swap_state.stdout != ''

# /swap.img       none    swap    sw      0       0
- name: Get result_grepc_swap
  shell: grep -v "\s*#" /etc/fstab | awk '{print $3}' | grep swap -c
  register: result_grepc_swap
  check_mode: false
  changed_when: false
  ignore_errors: true

- name: Disable swap (/etc/fstab)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: result_grepc_swap.stdout != '0'
