- name: Load kernel module for kubeadm
  modprobe:
    name: br_netfilter
    state: present

- name: Put br_netfilter.conf
  lineinfile:
    path: "/etc/modules-load.d/{{ item }}.conf"
    line: "{{ item }}"
    create: true
  with_items:
    - br_netfilter

- name: Put k8s.conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/k8s.conf
    state: present
  with_items:
    - name: net.bridge.bridge-nf-call-ip6tables
      value: 1
    - name: net.bridge.bridge-nf-call-iptables
      value: 1
